### ISSUE TITLE
996 不考虑员工的感受

### ISSUE THREAD

**Issue by sunhesong** [997icu/996.ICU#12759]
996的公司实在是自私啊，不知道是跟风还是怎么回事，只为自己公司的私利，而导致员工处于水深火热之中，更无视国家法律，当谈及有利公司的规章制度的时候搬法律比谁都快，当谈及个人的利益的时候，公司就找各种理由逃避，无视法律。。。

**Comment by Mr-Luxry** [comment]
我觉得你有违社会主义核心价值观，小心被和谐了
