### ISSUE TITLE
[趣头条招聘高级golang工程师] [not 996]!

### ISSUE THREAD

**Issue by json7** [997icu/996.ICU#12810]
邮箱 :json7@foxmail.com
地点:上海\北京

**Comment by lhc1999222** [comment]
这广告····秀

**Comment by 345927642** [comment]
997?

**Comment by Yanxinlong** [comment]
趣头条和头条有什么关系？

**Comment by json7** [comment]
周六如果需要加班,是给工资的

**Comment by json7** [comment]
> 这广告····秀

早晨一般10~10:30,  正常下班是7点. 8:30下班给晚餐餐补

**Comment by reasonsolo** [comment]
之前面到趣头条HRBP
开头就说公司需要大小周，问工作时间就变成不强制周末加班了，打自己脸还是蛮快的
问过几个里面的同事，有说8点半下班，有10点下班的
打广告的麻烦问问自己良心
