### ISSUE TITLE
996的工作，生活还剩下什么？

### ISSUE THREAD

**Issue by livisun** [997icu/996.ICU#1683]
工作是为支撑你生活的花销，让你体面而尊严的活着。国内人们拼命的工作，工作和生活混在一起，甚至只有工作，想着赚够了钱再怎么怎么样，然后赚了钱身体不行了，那这笔钱看病。而国外，他们的观念里生活是大于工作的，他们享受每一天的生活，工作和生活分的很清楚，工作只是他们每天生活的一小部分。 我想说的是，虽然国情如此，但怎么应该向健全的体制去发展，996是个什么玩意儿？资本家吃人了。。

**Comment by a119347** [comment]
毕竟大家都是在为社会主义事业而奋斗,所以估计ZF即使知道也睁一眼闭一眼吧,尤其大公司每年交那么多税

**Comment by GoromitLeo** [comment]
大家都闲着那怎么赶英超美啊
