### ISSUE TITLE
你在Issues的抵制和口嗨毫无意义！

### ISSUE THREAD

**Issue by EzrealJ** [997icu/996.ICU#2447]
如题。
你在这里的抵制、呼吁、宣言、倡议，包括但不限于这些方式，是没有任何意义的。这个现状不是抗议就可以解决的。需要政府监管才有改变现状的可能。
在这里口嗨的人，呼吁你抵制996，但你找不到工作，他们也不会养你。
流量和声音不应该在这里。
在哪里发声才有可能解决这个问题？
传送门:

http://www.gov.cn/hudong/xzlwh.htm
![image](https://user-images.githubusercontent.com/28976837/55123967-89e84180-513f-11e9-9d3e-47cd0f357a08.png)

**Comment by EzrealJ** [comment]
@996icu

**Comment by YJMQN** [comment]
nice

**Comment by netsman1030** [comment]
都不是傻子了。想抄水表吗？

**Comment by EzrealJ** [comment]
> 都不是傻子了。想抄水表吗？
为何会查水表?通过正确的途径反映问题有何不妥

**Comment by netsman1030** [comment]
> > 都不是傻子了。想抄水表吗？
> > 为何会查水表?通过正确的途径反映问题有何不妥

你明不明白为啥国内没有工会，就是为了让你没有正确的途径反映问题
现在但凡996新闻都有华为手机的工贼来洗地，甚至骂你不愿意奋斗，知道为什么吗

知不知道上头最支持的就是华为这种发明996的企业？

**Comment by netsman1030** [comment]
> > 都不是傻子了。想抄水表吗？
> > 为何会查水表?通过正确的途径反映问题有何不妥

为什么这种话题没有发生在知乎 贴吧 天涯
反而跑到了没有实名认证的github？
因为上头就是鼓励企业996！！！！

你还走所谓正规途径去举报。鼓励大家抱团
寻xin滋事的口袋等着你

**Comment by EzrealJ** [comment]
当你使用"上头支持"的词汇的时候，你有没有考虑过你的用词不当？
我，单方面认为 在这里口嗨才是寻衅滋事，迟早毁了github。
我，单方面认为 通过政府门户给予的渠道反馈没有任何问题。
你可以认同我，也可以反对我，都是你的自由。

**Comment by netsman1030** [comment]
> 当你使用"上头支持"的词汇的时候，你有没有考虑过你的用词不当？
> 我，单方面认为 在这里口嗨才是寻衅滋事，迟早毁了github。
> 我，单方面认为 通过政府门户给予的渠道反馈没有任何问题。
> 你可以认同我，也可以反对我，都是你的自由。

政府就是我们的上头，这里不是西方，政府不是和我们平起平坐的。
不管说什么 github都是github
但是单方面认为还鼓动大家往火坑里跳，那基本跟找死差不多了
同时寻衅滋事的定义也不是由你定义的，你我都没有资格。那是上头定义的。
